@startjson
title List of Available Genres Response
!theme sunlust

[
  {
    "name": "ROCK",
    "description": "Rock Music"
  },
  {
    "name": "POP",
    "description": "Popular Music"
  },
  {
    "name": "JAZZ",
    "description": "Jazz Music"
  },
  "..."
]
@endjson
