@startuml ERD

!theme vibrant

entity User {
  + user_id : UUID <<PK>>
  --
  * username : VARCHAR <<UNIQUE>>
  * password : VARCHAR
  * name : VARCHAR
  * surname : VARCHAR
}

entity Album {
  + album_id : INT <<PK>>
  --
  * title : VARCHAR
  * artist : VARCHAR
  * publication_year : INT
  * image_path : VARCHAR
}

entity Song {
  + song_id : INT <<PK>>
  --
  * title : VARCHAR
  * genre : VARCHAR
  * audio_file_path : VARCHAR
  # album_id : INT <<FK>>
  # owner_user_id : UUID <<FK>>
}

entity Playlist_medadata {
  + playlist_id : INT <<PK>>
  --
  * title : VARCHAR
  * creation_date : DATE
  # owner_user_id : UUID <<FK>>
}

entity Playlist_content {
  # playlist_id : INT <<FK>> <<PK>>
  # song_id : INT <<FK>> <<PK>>
}

User "1" -- "0..*" Song : owns/uploads
User "1" -- "0..*" Playlist_medadata : creates
Album "1" -- "1..*" Song : contains
Playlist_medadata "1" -- "0..*" Playlist_content : has
Song "1" -- "0..*" Playlist_content : belongs to

@enduml
